package se.lexicon.order.component.domain;

import com.so4it.annotation.Allowed;
import com.so4it.common.util.object.Required;
import com.so4it.common.util.object.ValueObject;

import java.io.Serializable;

public class OrderBook extends ValueObject implements Serializable {

    @Allowed(types = {Allowed.Type.NULLABLE})
    private String id;

    private String instrument;

    private  Integer noOfItems;

    private  Money minMaxValue;
    //Money maxValue if BUY, minValue if SELL;

    private Phase phase = Phase.UNKNOWN;

    private Side side; // Sell or Buy

    private OrderBook() {
    }

    private OrderBook (Builder builder) {
        this.id = builder.id;
        this.instrument = Required.notNull(builder.instrument,"instrument");
        this.noOfItems = Required.notNull(builder.noOfItems,"noOfItems");
        this.minMaxValue = Required.notNull(builder.minMaxValue,"minMaxValue");
        this.phase = Required.notNull(builder.phase,"phase");
        this.side = Required.notNull(builder.side,"sellOrder");
    }

    @Override
    protected Object[] getIdFields() {
        return new Object[]{id, instrument, noOfItems, minMaxValue, phase, side};
    }

    //@Allowed(minMaxValue = "Auto generated by GS",types = {Allowed.Type.NULLABLE})
    public String getId() {
        return id;
    }

    public String getInstrument() {
        return instrument;
    }

    public Integer getNoOfItems() {
    return noOfItems;
}

    public Money getMinMaxValue() {
        return minMaxValue;
    }

    public Phase getPhase() {
        return phase;
    }

    public Side getSide() {
        return side;
    }

    public static Builder builder(){
        return new Builder();
    }

    public static class Builder implements com.so4it.common.builder.Builder<OrderBook>{

        private String id;

        private String instrument;

        private Integer noOfItems;

        private Money minMaxValue;
        //Money max or min Value;

        private Phase phase;

        private Side side;

        public Builder withId(String id){
            this.id = id;
            return this;
        }

        public Builder withInstrument(String instrument){
            this.instrument = instrument;
            return this;
        }

        public Builder withNoOfItems(Integer noOfItems){
            this.noOfItems = noOfItems;
            return this;
        }

        public Builder withMinMaxValue(Money value){
            this.minMaxValue = value;
            return this;
        }

        public Builder withPhase(Phase phase){
            this.phase = phase;
            return this;
        }

        public Builder withSide(Side sellOrder){
            this.side = sellOrder;
            return this;
        }

        @Override
        public OrderBook build() {
            return new OrderBook(this);
        }
    }
}
