package se.lexicon.order.component.event;

import com.gigaspaces.annotation.pojo.SpaceClass;
import com.gigaspaces.annotation.pojo.SpaceFifoGroupingProperty;
import com.gigaspaces.annotation.pojo.SpaceId;
import com.gigaspaces.annotation.pojo.SpaceRouting;
import com.so4it.annotation.Allowed;
import com.so4it.common.util.object.Required;
import com.so4it.component.entity.AbstractEntityBuilder;
import com.so4it.component.entity.IdEntity;
import se.lexicon.order.component.domain.Order;

import java.math.BigDecimal;

/**
 *
 * @author Magnus Poromaa {@literal <mailto:magnus.poromaa@so4it.com/>}
 */
@SpaceClass
public class PlaceOrderEvent extends IdEntity<String> {

    @Allowed(value = "Auto generated by GS", types = {Allowed.Type.NULLABLE})
    private String id;

    private String ssn;

    private Order order;

    private Integer counter;

    private PlaceOrderEvent() {
    }

    private PlaceOrderEvent(Builder builder) {
        this.id = builder.id;
        this.ssn = Required.notNull(builder.ssn,"ssn",builder.isTemplate());
        this.order = Required.notNull(builder.order,"order",builder.isTemplate());
        this.counter = Required.notNull(builder.counter,"counter",builder.isTemplate());
    }

    @Override
    @SpaceId(autoGenerate = true)
    public String getId() {
        return id;
    }

    private void setId(String id) {
        this.id = id;
    }

    @SpaceRouting
    @SpaceFifoGroupingProperty
    public String getSsn() { return ssn; }

    private void setSsn(String ssn) { this.ssn = ssn; }

    public Order getOrder() {
        return order;
    }

    private void setOrder(Order order) {
        this.order = order;
    }

    public Integer getCounter() {
        return counter;
    }

    private void setCounter(Integer counter) {
        this.counter = counter;
    }

    public static Builder builder() {
        return new Builder(false);
    }

    public static Builder templateBuilder() {
        return new Builder(true);
    }


    public static class Builder extends AbstractEntityBuilder<PlaceOrderEvent> {

        private String id;

        private String ssn;

        private Order order;

        private Integer counter;

        public Builder(boolean template) {
            super(template);
        }

        public PlaceOrderEvent.Builder withId(String id) {
            this.id = id;
            return this;
        }

        public PlaceOrderEvent.Builder withSsn(String ssn) {
            this.ssn = ssn;
            return this;
        }

        public PlaceOrderEvent.Builder withOrder(Order order) {
            this.order = order;
            return this;
        }

        public PlaceOrderEvent.Builder withCounter(Integer counter) {
            this.counter = counter;
            return this;
        }


        @Override
        public PlaceOrderEvent build() {
            return new PlaceOrderEvent(this);
        }
    }
}
