package se.lexicon.order.component.entity;

import com.gigaspaces.annotation.pojo.SpaceClass;
import com.gigaspaces.annotation.pojo.SpaceId;
import com.gigaspaces.annotation.pojo.SpaceRouting;
import com.so4it.annotation.Allowed;
import com.so4it.common.util.object.Required;
import com.so4it.component.entity.AbstractEntityBuilder;
import com.so4it.component.entity.IdEntity;

@SpaceClass
public class DealEntity extends IdEntity<String> {

    @Allowed(value="Auto generated by GS",types = {Allowed.Type.NULLABLE})
    private String id;

    private String instrument;

    private String buyOrderId;

    private String sellOrderId;

    private DealEntity(){

    }
    
    private DealEntity(Builder builder){
        this.id=builder.id;
        this.instrument= Required.notNull(builder.instrument,"instrument",builder.isTemplate());
        this.buyOrderId=Required.notNull(builder.buyOrderId,"buyOrderId",builder.isTemplate());
        this.sellOrderId=Required.notNull(builder.sellOrderId,"sellOrderId",builder.isTemplate());
    }


    @Override
    @SpaceId(autoGenerate = true)
    public String getId() {
        return id;
    }

    private void setId(String id){
        this.id =id;
    }

    @SpaceRouting
    public String getInstrument(){
        return instrument;
    }

    private void setInstrument(String instrument){
        this.instrument = instrument;

    }

    public String getBuyOrderId(){
        return buyOrderId;
    }

    private void setBuyOrderId(String buyOrderId){
        this.buyOrderId=buyOrderId;
    }

    public String getSellOrderId(){
        return sellOrderId;
    }

    private void setSellOrderId(String sellOrderId){
        this.sellOrderId=sellOrderId;
    }

    public static Builder builder(){
        return new Builder(false);
    }

    public static Builder templateBuilder(){
        return new Builder(true);
    }

    public static class Builder extends AbstractEntityBuilder<DealEntity> {

        private String id;
        private String instrument;
        private String buyOrderId;
        private String sellOrderId;

        public Builder(boolean template){
            super(template);
        }

        public DealEntity.Builder withId(String id){
            this.id=id;
            return this;
        }

        public DealEntity.Builder withInstrument(String instrument){
            this.instrument=instrument;
            return this;
        }

        public DealEntity.Builder withBuyOrderId(String buyOrderId){
            this.buyOrderId=buyOrderId;
            return this;
        }

        public DealEntity.Builder withSellOrderId(String sellOrderId){
            this.sellOrderId =sellOrderId;
            return this;
        }

        @Override
        public DealEntity build(){
            return new DealEntity(this);
        }
    }
}
